// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TmBussines.WebMvcTest.Data;

#nullable disable

namespace TmBussines.WebMvcTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221209113329_seeddata")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TmBussines.WebMvcTest.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TodoItem");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "In Meeting need to discuss some points.",
                            IsComplete = true,
                            Name = "Meeting with managment"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "List of this item buy.",
                            IsComplete = false,
                            Name = "Go for shopping"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Here task to ask to do on call.",
                            IsComplete = true,
                            Name = "Call to some one for do some task"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
